spring.application.name=crypto-exchange
server.port=8400

spring.jpa.show-sql=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true

#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#docker
eureka.client.service-url.defaultZone=http://host.docker.internal:8761/eureka

#lep ispis poruka
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never