spring.application.name= api-gateway
server.port = 8765

#eureka.client.serviceUrl.defaultZone = http://localhost:8761/eureka
#docker
eureka.client.service-url.defaultZone=http://host.docker.internal:8761/eureka/

spring.main.web-application-type=reactive


#lep ispis poruka
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never
