spring.application.name=bank-account
server.port = 8200

spring.datasource.url = jdbc:h2:mem:testdb
spring.h2.console.enabled= true
spring.jpa.defer-datasource-initialization=true
spring.cloud.compatibility-verifier.enabled=false

#eureka.client.serviceUrl.defaultZone = http://localhost:8761/eureka

#docker host.docker.internal?
eureka.client.service-url.defaultZone=http://host.docker.internal:8761/eureka/

#lep ispis poruka
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never